server:
  port: 7001
spring:
  application:
    name: cms-system-eureka-server
eureka:
  instance:
    hostname: eureka.jyonline.com
    prefer-ip-address: true
    instance-id: cms-system-eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}