server:
  port: 8005
spring:
  application:
    name: cms-system-file-manage
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: cmssystem
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 150
    height: 150
  tracker-list: 192.168.2.103:22122
  pool:
    max-total: -1
    max-wait-millis: 5000
    max-total-per-key: 50
    max-idle-per-key: 10
eureka:
  client:
    service-url: http://eureka.jyonline.com:7001/eureka/
  instance:
    instance-id: cms-system-file-manage