server:
  port: 8004
spring:
  application:
    name: cms-system-course-manage
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cms_course?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false&autoReconnectForPools=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: cmssystem
eureka:
  client:
    service-url:
      defaultZone: http://eureka.jyonline.com:7001/eureka/
  instance:
    instance-id: cms-system-course-manage
    prefer-ip-address: true
course-preview:
  siteId: 5a751fab6abb5044e0d19ea1
  templateId: 5aec5dd70e661808240ab7a6
  pagePhysicalPath: E:/workspace/static_web/jiuyunonline/xc-ui-pc-static-portal
  pageWebPath: /course/detail/
  dataUrl: http://api.jyonline.com/course/view/get/
  previewUrl: http://www.jyonline.com/cms/preview/
