server:
  port: 8001
spring:
  application:
    name: cms-system-service-manage
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: cmssystem
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.0.87
    port: 5672
    username: root
    password: root
cms:
  mq:
    exchange: site.html
eureka:
  client:
    service-url:
      defaultZone: http://eureka.jyonline.com:7001/eureka/
  instance:
    instance-id: cms-system-service-manage
    prefer-ip-address: true