server:
  port: 8004
spring:
  application:
    name: cms-system-course-manage
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cms_course?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false&autoReconnectForPools=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: cmssystem